% DEMEIGENVOICELATENT Show latent space of eigenvoices.
%
% COPYRIGHT : Jon Barker, 2009
%
% MODIFICATIONS : Neil D. Lawrence, 2009

% SYNTH

global visualiseInfo

[durm, durv] = synthLoadData('dur');
[cmpm, cmpv] = synthLoadData('cmp');
fhandle = figure;

a = ver('matlab');
if strcmp(a.Version, '7.0.1')
  menu = 'listbox';
else
  menu = 'popupmenu';
end


visualiseInfo.utt_popup = uicontrol('Style', menu, ...
                                    'Parent',fhandle, ...
                                    'Units', 'normalized', ...
                                    'Position',[0.02 0.02 0.2 0.05], ...  
                                    'String', {'ay', 'place', 'bbaf3s', 'pbav3s'}, ...
                                    'Min', 1, 'Max', ...
                                    4, 'Value', 3);

h = visualiseInfo.utt_popup;
if(strcmp(menu, 'listbox'))
  set(h, 'listboxtop', get(h, 'value'));
%  set(h, 'callback', 'set(h, ''listboxtop'', get(h, ''value''))');
end

visualiseInfo.datatype_popup = uicontrol('Style', menu, ...
                              'Parent', fhandle, ...
                              'Units','normalized', ...
                              'Position',[0.22 0.02 0.2 0.05], ...
                              'String',{'Duration', 'Vocal'}, ...
                              'Min', 1, ...
                              'Max', 2, ...
                              'Value', 2);

h = visualiseInfo.datatype_popup;
if(strcmp(menu, 'listbox'))
  set(h, 'listboxtop', get(h, 'value'));
%  set(h, 'callback', 'set(h, ''listboxtop'', get(h, ''value''))');
end

visualiseInfo.d1_popup = uicontrol('Style', menu, ...
                        'Parent', fhandle, ...
                        'Units','normalized', ...
                        'Position',[0.42 0.02 0.2 0.05], ...
                        'String',{' X: 1 ',' X: 2 ',' X: 3 ',' X: 4 '}, ...
                        'Min', 1, ...
                        'Max', 4, ...
                        'Value', 1);
h = visualiseInfo.d1_popup;
if(strcmp(menu, 'listbox'))
  set(h, 'listboxtop', get(h, 'value'));
%  set(h, 'callback', 'set(h, ''listboxtop'', get(h, ''value''))');
end

visualiseInfo.d2_popup = uicontrol('Style', menu, ...
                        'Parent', fhandle, ...
                        'Units', 'normalized', ...
                        'Position', [0.62 0.02 0.2 0.05], ...
                        'String',{' Y: 1 ',' Y: 2 ',' Y: 3 ',' Y: 4 '}, ...
                        'Min', 1, ...
                        'Max', 4, ...
                        'Value', 2);
h = visualiseInfo.d2_popup;
if(strcmp(menu, 'listbox'))
  set(h, 'listboxtop', get(h, 'value'));
%  set(h, 'callback', 'set(h, ''listboxtop'', get(h, ''value''))');
end
  

uicontrol('Parent', fhandle, ...
          'Units','normalized', ...
          'Callback','synthEigenvoiceCallback', ...
          'Position',[0.82 0.02 0.15 0.05], ...
          'String','Run');


visualiseInfo.spec1plot = subplot('Position',[0.01, 0.8, 0.98, 0.2]);
set(visualiseInfo.spec1plot, 'Visible','off');
visualiseInfo.spec2plot = subplot('Position',[0.01, 0.6, 0.98, 0.2]);
set(visualiseInfo.spec2plot, 'Visible','off');


visualiseInfo.plotAxes = subplot('Position',[0.01, 0.15, 0.98, 0.45]);
set(visualiseInfo.plotAxes, 'Visible','off');
visualiseInfo.durm=durm;
visualiseInfo.durv=durv;
visualiseInfo.cmpm=cmpm;
visualiseInfo.cmpv=cmpv;

set(gcf,'UserData', visualiseInfo)


