% DEMEIGENVOICELATENT Show latent space of eigenvoices.
%
% COPYRIGHT : Jon Barker, 2009
%
% MODIFICATIONS : Neil D. Lawrence, 2009

% SYNTH

disp('Loading duration means...');
durm = load([synthDirectory 'data/dur.mean']);
disp('Loading duration variances...');
durv = load([synthDirectory 'data/dur.var']);
%  cmpm = load('data/dur.mean');
%  cmpv = load('data/dur.var');
disp('Loading mfcc means...');
cmpm=load([synthDirectory 'data/cmp.mean']);
disp('Loading mfcc variances...');
cmpv=load([synthDirectory 'data/cmp.var']);

fhandle = figure;


ud.utt_popup = uicontrol('Style', 'listbox', ...
                         'Parent',fhandle, ...
                         'Units','points', ...
                         'Position',[20 2 80 15], ...
                         'String',['   ay ';' place';'bbaf3s';'pbav3s'], ...
                         'Min', 0, 'Max', ...
                         0, 'Value', 3);

ud.datatype_popup = uicontrol('Style', 'listbox', ...
                              'Parent', fhandle, ...
                              'Units','points', ...
                              'Position',[110 2 80 15], ...
                              'String',['Duration';'  Vocal ';], ...
                              'Min', 0, ...
                              'Max', 0, ...
                              'Value', 2);

ud.d1_popup = uicontrol('Style', 'listbox', ...
                        'Parent', fhandle, ...
                        'Units','points', ...
                        'Position',[220 2 50 15], ...
                        'String',[' X: 1 ';' X: 2 ';' X: 3 ';' X: 4 '], ...
                        'Min', 0, ...
                        'Max', 0, ...
                        'Value', 1);

ud.d2_popup = uicontrol('Style', 'listbox', ...
                        'Parent', fhandle, ...
                        'Units', 'points', ...
                        'Position', [280 2 50 15], ...
                        'String',[' Y: 1 ';' Y: 2 ';' Y: 3 ';' Y: 4 '], ...
                        'Min', 0, ...
                        'Max', 0, ...
                        'Value', 2);
  

uicontrol('Parent', fhandle, ...
          'Units','points', ...
          'Callback','synthEigenvoiceCallback', ...
          'Position',[360 2 80 15], ...
          'String','Run');

 
ud.spec1plot = subplot('Position',[0.01, 0.8, 0.98, 0.2]);
set(ud.spec1plot, 'Visible','off');
ud.spec2plot = subplot('Position',[0.01, 0.6, 0.98, 0.2]);
set(ud.spec2plot, 'Visible','off');
ud.spaceplot = subplot('Position',[0.01, 0.1, 0.98, 0.5]);
set(ud.spaceplot, 'Visible','off');
ud.durm=durm;
ud.durv=durv;
ud.cmpm=cmpm;
ud.cmpv=cmpv;

set(gcf,'UserData',ud)

