% DEMPROJECTVOICES Demonstrate projection of voices onto reduced dimension.
 
% COPYRIGHT : Jon Barker, 2009
%
% MODIFICATIONS : Neil D. Lawrence, 2009

% SYNTH

% Load in the processed grid data.

[cmpm, cmpv] = synthLoadData('cmp');

fhandle = figure;

a = ver('matlab');
if strcmp(a.Version, '7.0.1')
  menu = 'listbox';
else
  menu = 'popupmenu';
end
ud.utt_popup = uicontrol('Style', menu, ...
                         'Parent',fhandle, ...
                         'Units','normalized', ...
                         'Position',[0.02, 0.02, 0.2, 0.05], ...
                         'String',{'ay', 'place', 'bbaf3s', 'pbav3s'}, ...
                         'Min', 0, ...
                         'Max', 0, ...
                         'visible', 'off', ...
                         'Value', 3);

h = ud.utt_popup;
if(strcmp(menu, 'listbox'))
  set(h, 'listboxtop', get(h, 'value'));
end

% ID Control
uicontrol('Style', 'text', ...
          'Parent', fhandle, ...
          'Units','normalized',...
          'Position',[0.24 0.02 0.05 0.05], ...
          'String', 'ID');

ud.id_edit = uicontrol('Style', 'edit', ...
                       'Parent', fhandle, ...
                       'Units','normalized', ...
		       'Position', [0.29 0.02 0.05 0.05], ...
                       'Min', 0, ...
                       'Max', 0, ...
                       'String', '1');

% NDim Control
uicontrol('Style', 'text', ...
          'Parent', fhandle, ...
          'Units', 'normalized', ...
          'Position',[0.39 0.02 0.1 0.05], ...
          'String', 'NDims');


ud.ndims_edit = uicontrol('Style', 'edit', ...
                          'Parent', fhandle, ...
                          'Units','normalized', ...
                          'Position', [0.49 0.02 0.05 0.05], ...
                          'Min', 0, ...
                          'Max', 0, ...
                          'String', '0');


% Original button
uicontrol('Parent', fhandle, ...
          'Units','normalized', ...
          'Callback', 'synthProjectionCallback(''orig'');', ...
          'Position', [0.54 0.02 0.15 0.05], ...
          'String', 'Original');

% Projected button
uicontrol('Parent', fhandle, ...
          'Units','normalized', ...
          'Callback','synthProjectionCallback(''reduced'');', ...
          'Position',[0.69 0.02 0.15 0.05], ...
          'String','Projected');


% Error
ud.error_text=uicontrol('Style', 'text', ...
                        'Parent', fhandle, ...
                        'Units','normalized',...
                        'Position',[0.84 0.02 0.1 0.05], ...
                        'String', '-----');

% Error
ud.mode_checkbox=uicontrol('Style', 'checkbox', ...
                           'Parent', fhandle, ...
                           'Units','normalized', ...
                           'Position', [0.94 0.02 0.04 0.05]);



ud.spec1plot = subplot('Position', [0.01, 0.65, 0.98, 0.35]);
set(ud.spec1plot, 'Visible','off')
ud.spec2plot = subplot('Position', [0.01, 0.15, 0.98, 0.35]);
set(ud.spec2plot, 'Visible','off')

ud.cmpm=cmpm;
ud.cmpv=cmpv;

set(ud.utt_popup, 'visible', 'on', 'value', 4)

set(gcf,'UserData',ud)
