% DEMPROJECTVOICES Demonstrate projection of voices onto reduced dimension.
 
% COPYRIGHT : Jon Barker, 2009
%
% MODIFICATIONS : Neil D. Lawrence, 2009

% SYNTH

% Load in the processed grid data.
disp('Loading mfcc means...');
cmpm=load([synthDirectory 'data/cmp.mean']);
disp('Loading mfcc variances...');
cmpv=load([synthDirectory 'data/cmp.var']);

fhandle = figure;

ud.utt_popup = uicontrol('Style', 'listbox', ...
                         'Parent',fhandle, ...
                         'Units','points', ...
                         'Position',[20 2 80 15], ...
                         'String',['   ay ';' place';'bbaf3s';'pbav3s'], ...
                         'Min', 0, ...
                         'Max', 0, ...
                         'Value', 3);

% ID Control
uicontrol('Style', 'text', ...
          'Parent', fhandle, ...
          'Units','points',...
          'Position',[110 2 40 15], ...
          'String', 'ID');

ud.id_edit = uicontrol('Style', 'edit', ...
                       'Parent', fhandle, ...
                       'Units','points', ...
		       'Position', [150 2 40 15], ...
                       'Min', 0, ...
                       'Max', 0, ...
                       'String', '1');

% NDim Control
uicontrol('Style', 'text', ...
          'Parent', fhandle, ...
          'Units', 'points', ...
          'Position',[190 2 40 15], ...
          'String', 'NDims');


ud.ndims_edit = uicontrol('Style', 'edit', ...
                          'Parent', fhandle, ...
                          'Units','points', ...
                          'Position', [230 2 40 15], ...
                          'Min', 0, ...
                          'Max', 0, ...
                          'String', '0');


% Original button
uicontrol('Parent', fhandle, ...
          'Units','points', ...
          'Callback', 'synthProjectionCallback(''orig'');', ...
          'Position', [280 2 80 15], ...
          'String', 'Original');

% Projected button
uicontrol('Parent', fhandle, ...
          'Units','points', ...
          'Callback','synthProjectionCallback(''reduced'');', ...
          'Position',[360 2 80 15], ...
          'String','Projected');


% Error
ud.error_text=uicontrol('Style', 'text', ...
                        'Parent', fhandle, ...
                        'Units','points',...
                        'Position',[450 2 60 15], ...
                        'String', '-----');

% Error
ud.mode_checkbox=uicontrol('Style', 'checkbox', ...
                           'Parent', fhandle, ...
                           'Units','points', ...
                           'Position', [520 2 15 15]);



ud.spec1plot = subplot('Position', [0.01, 0.55, 0.98, 0.4]);
set(ud.spec1plot, 'Visible','off')
ud.spec2plot = subplot('Position', [0.01, 0.10, 0.98, 0.4]);
set(ud.spec2plot, 'Visible','off')

ud.cmpm=cmpm;
ud.cmpv=cmpv;

set(gcf,'UserData',ud)
